root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - next/core-web-vitals
rules:
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
  '@typescript-eslint/no-explicit-any': error
  '@typescript-eslint/no-unused-vars': error
settings:
  react:
    version: detect
